/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.welbyseely;

public class LibraryTest {
/*    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
*/
}

